#!/usr/bin/env bash
#a script that install nginx in remote server
sudo apt-get -y update
sudo apt-get -y upgread
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /var/www/
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo ufw alllow "Nginx HTTP"
sudo service nginx restart
