#!/usr/bin/env bash
# Install nginx and and make it return a page with a string 'Holberton School'

sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "/listen 80 default_server/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
                          