#!/usr/bin/env bash
# a bash script that configure ufw and block all the incoming trafic except few tcps
sudo apt-get install -y ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw enable